# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: DataHub iRODS ruleset - Python package

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest bandit pylint
      #        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Bandit (static security check)
        run: |
          bandit -r ./python/
      #    - name: Lint with flake8
      #      run: |
      #        # stop the build if there are Python syntax errors or undefined names
      #        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      #    - name: Run Pylint
      #      run: |
      #        pylint --max-line-length=120 --exit-zero ./irodsrulewrapper/
      #    - name: Test with pytest
      #      run: |
      #        pytest
      - name: Report Status to Dean
        if: ${{ always() && github.event.pusher.name == 'deanlinssen' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_users: ${{ secrets.SLACK_DEAN_ID }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK }}
      - name: Report Status to Daniel
        if: ${{ always() && github.event.pusher.name == 'danieltheunissen' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_users: ${{ secrets.SLACK_DANIEL_ID }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK }}
      - name: Report Status to Jonathan
        if: ${{ always() && github.event.pusher.name  == 'JonathanMELIUS' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_users: ${{ secrets.SLACK_JONATHAN_ID }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK }}
      - name: Report Status general
        if: ${{ always() && github.event.pusher.name != 'deanlinssen' && github.event.pusher.name != 'danieltheunissen' && github.event.pusher.name != 'JonathanMELIUS' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK }}