name: DataHub iRODS ruleset - Python package

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: python:2.7.18-buster
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade "pip < 21.0" 
          python -m pip install flake8 pylint bandit==1.6.2
          python -m pip install .
      - name: Run Bandit (static security check)
        run: |
          bandit -r ./datahubirodsruleset/
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./datahubirodsruleset --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./datahubirodsruleset --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run Pylint
        run: |
          pylint --max-line-length=120 --exit-zero ./datahubirodsruleset/
      - name: Report Status to Dean
        if: ${{ always() && github.event.pusher.name == 'deanlinssen' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_users: ${{ secrets.SLACK_DEAN_ID }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK }}
      - name: Report Status to Daniel
        if: ${{ always() && github.event.pusher.name == 'danieltheunissen' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_users: ${{ secrets.SLACK_DANIEL_ID }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK }}
      - name: Report Status to Jonathan
        if: ${{ always() && github.event.pusher.name  == 'JonathanMELIUS' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_users: ${{ secrets.SLACK_JONATHAN_ID }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK }}
      - name: Report Status general
        if: ${{ always() && github.event.pusher.name != 'deanlinssen' && github.event.pusher.name != 'danieltheunissen' && github.event.pusher.name != 'JonathanMELIUS' }}
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK }}